export const mockPosts = [
    {
        id: "post-1",
        title: "AI-Assisted Detection of Arrhythmia in ECG",
        domain: "Cardiology Imaging & Data",
        authorId: "eng-1",
        authorName: "Dr. Sarah Chen",
        authorRole: "Engineer",
        explanation: "Developing a deep learning model to detect early signs of arrhythmia. Model accuracy is currently 92%, but needs refinement on edge cases.",
        expertiseNeeded: "Looking for a clinical cardiologist to help define edge cases, label ambiguous data, and validate outputs against clinical standards.",
        projectStage: "concept validation",
        commitmentLevel: "advisor",
        collaborationType: "advisor",
        confidentiality: "public",
        status: "Active",
        country: "Germany",
        city: "Berlin",
        createdAt: "2026-02-20T10:00:00Z",
        expiryDate: "2026-06-20T10:00:00Z",
        highLevelIdea: "We use a novel transformer architecture on 12-lead ECG data. Need clinical insights to avoid false positives.",
        interestCount: 0,
        meetingCount: 0
    },
    {
        id: "post-2",
        title: "Smart VR Environment for Stroke Rehabilitation",
        domain: "Neurology/Rehabilitation",
        authorId: "doc-1",
        authorName: "Dr. James Miller",
        authorRole: "Healthcare Professional",
        explanation: "Current physical therapy for stroke patients lacks engagement and tracking. We want to test a VR system that gamifies repetitive exercises while collecting biomechanical data.",
        expertiseNeeded: "Need an engineer/developer with Unity and VR/XR background to build the prototype.",
        projectStage: "idea",
        commitmentLevel: "co-founder",
        collaborationType: "research partner",
        confidentiality: "meeting-only",
        status: "Active",
        country: "Switzerland",
        city: "Zurich",
        createdAt: "2026-02-25T14:30:00Z",
        expiryDate: "2026-08-25T14:30:00Z",
        highLevelIdea: "Details discussed in meeting only.",
        interestCount: 0,
        meetingCount: 0
    },
    {
        id: "post-3",
        title: "Non-invasive Glucose Monitoring Wearable",
        domain: "Endocrinology",
        authorId: "eng-2",
        authorName: "Michael Chang",
        authorRole: "Engineer",
        explanation: "We've developed a sensor that measures interstitial fluid glucose through skin using Raman spectroscopy. Prototype is functional but needs clinical validation.",
        expertiseNeeded: "Looking for an endocrinologist to design clinical trials and validate sensor lag against CGM devices.",
        projectStage: "prototype developed",
        commitmentLevel: "research partner",
        collaborationType: "research partner",
        confidentiality: "meeting-only",
        status: "CLOSED",
        country: "United Kingdom",
        city: "London",
        createdAt: "2026-01-15T09:12:00Z",
        expiryDate: "2026-05-15T09:12:00Z",
        highLevelIdea: "Details discussed in meeting only.",
        interestCount: 0,
        meetingCount: 0
    },
    {
        id: "post-4",
        title: "AI-Powered Radiology Report Generator",
        domain: "Oncology",
        authorId: "eng-3",
        authorName: "Anna Weber",
        authorRole: "Engineer",
        explanation: "Building an NLP system that creates structured radiology reports from free-text findings. Currently supports chest CT and MRI brain scans with 88% agreement with expert radiologists.",
        expertiseNeeded: "Need a radiologist or oncologist to validate report quality, define edge cases, and ensure clinical terminology accuracy.",
        projectStage: "concept validation",
        commitmentLevel: "advisor",
        collaborationType: "advisor",
        confidentiality: "public",
        status: "Active",
        country: "Germany",
        city: "Munich",
        createdAt: "2026-02-18T08:00:00Z",
        expiryDate: "2026-07-18T08:00:00Z",
        highLevelIdea: "Transformer-based model fine-tuned on MIMIC-CXR dataset with custom attention heads for structured reporting.",
        interestCount: 0,
        meetingCount: 0
    },
    {
        id: "post-5",
        title: "Digital Twin for Personalized Drug Dosing",
        domain: "Pharmacology",
        authorId: "doc-2",
        authorName: "Prof. Elena Rodriguez",
        authorRole: "Healthcare Professional",
        explanation: "Pharmacogenomics data can predict drug metabolism but integrating this into bedside dosing decisions is complex. We need a simulation system that healthcare providers can use.",
        expertiseNeeded: "Looking for a software engineer experienced in simulation modeling, pharmacokinetics, or systems biology.",
        projectStage: "idea",
        commitmentLevel: "research partner",
        collaborationType: "research partner",
        confidentiality: "public",
        status: "Active",
        country: "Spain",
        city: "Barcelona",
        createdAt: "2026-02-26T11:00:00Z",
        expiryDate: "2026-09-26T11:00:00Z",
        highLevelIdea: "Open architecture approach — simulation engine takes genotype + vitals as input, outputs personalized loading dose suggestions.",
        interestCount: 0,
        meetingCount: 0
    },
    {
        id: "post-6",
        title: "Wearable Seizure Detection System",
        domain: "Neurology/Rehabilitation",
        authorId: "eng-4",
        authorName: "Dr. Lars Nilsson",
        authorRole: "Engineer",
        explanation: "A wrist-worn device that uses accelerometer + EDA data to detect tonic-clonic seizures in real-time. Current model has 94% sensitivity but needs clinical refinement.",
        expertiseNeeded: "Seeking a neurologist specializing in epilepsy to review detection algorithms and assist with IRB approval for pilot study.",
        projectStage: "pilot testing",
        commitmentLevel: "research partner",
        collaborationType: "research partner",
        confidentiality: "meeting-only",
        status: "Active",
        country: "Sweden",
        city: "Stockholm",
        createdAt: "2026-02-22T09:00:00Z",
        expiryDate: "2026-06-22T09:00:00Z",
        highLevelIdea: "Details discussed in meeting only.",
        interestCount: 0,
        meetingCount: 0
    }
];

export const mockUsers = [
    {
        id: "doc-1",
        name: "Dr. James Miller",
        email: "j.miller@med.uni-zurich.edu",
        role: "Healthcare Professional",
        institution: "University of Zurich",
        city: "Zurich",
        country: "Switzerland",
        registeredAt: "2026-01-10T08:00:00Z",
        status: "active",
        lastLogin: "2026-02-27T09:30:00Z"
    },
    {
        id: "eng-1",
        name: "Dr. Sarah Chen",
        email: "s.chen@tum.edu",
        role: "Engineer",
        institution: "Technical University of Munich",
        city: "Berlin",
        country: "Germany",
        registeredAt: "2026-01-05T14:00:00Z",
        status: "active",
        lastLogin: "2026-02-27T08:15:00Z"
    },
    {
        id: "eng-2",
        name: "Michael Chang",
        email: "m.chang@imperial.edu",
        role: "Engineer",
        institution: "Imperial College London",
        city: "London",
        country: "United Kingdom",
        registeredAt: "2026-01-12T10:00:00Z",
        status: "active",
        lastLogin: "2026-02-25T16:45:00Z"
    },
    {
        id: "eng-3",
        name: "Anna Weber",
        email: "a.weber@lmu.edu",
        role: "Engineer",
        institution: "LMU Munich",
        city: "Munich",
        country: "Germany",
        registeredAt: "2026-02-01T09:00:00Z",
        status: "active",
        lastLogin: "2026-02-27T07:00:00Z"
    },
    {
        id: "doc-2",
        name: "Prof. Elena Rodriguez",
        email: "e.rodriguez@ub.edu",
        role: "Healthcare Professional",
        institution: "University of Barcelona",
        city: "Barcelona",
        country: "Spain",
        registeredAt: "2026-02-15T12:00:00Z",
        status: "active",
        lastLogin: "2026-02-26T21:00:00Z"
    },
    {
        id: "eng-4",
        name: "Dr. Lars Nilsson",
        email: "l.nilsson@kth.edu",
        role: "Engineer",
        institution: "KTH Royal Institute of Technology",
        city: "Stockholm",
        country: "Sweden",
        registeredAt: "2026-02-10T07:00:00Z",
        status: "active",
        lastLogin: "2026-02-27T10:00:00Z"
    },

];

export const mockActivityLogs = [

    {
        id: "log-2",
        timestamp: "2026-02-27T09:30:00Z",
        userId: "doc-1",
        userName: "Dr. James Miller",
        role: "Healthcare Professional",
        actionType: "LOGIN",
        targetEntity: "session",
        result: "success",
        details: "User login from Zurich"
    },
    {
        id: "log-3",
        timestamp: "2026-02-27T08:15:00Z",
        userId: "eng-1",
        userName: "Dr. Sarah Chen",
        role: "Engineer",
        actionType: "LOGIN",
        targetEntity: "session",
        result: "success",
        details: "User login from Berlin"
    },
    {
        id: "log-4",
        timestamp: "2026-02-26T15:00:00Z",
        userId: "eng-3",
        userName: "Anna Weber",
        role: "Engineer",
        actionType: "POST_CREATE",
        targetEntity: "post-4",
        result: "success",
        details: "Created 'AI-Powered Radiology Report Generator'"
    },
    {
        id: "log-5",
        timestamp: "2026-02-26T14:00:00Z",
        userId: "doc-2",
        userName: "Prof. Elena Rodriguez",
        role: "Healthcare Professional",
        actionType: "POST_CREATE",
        targetEntity: "post-5",
        result: "success",
        details: "Created 'Digital Twin for Personalized Drug Dosing'"
    },
    {
        id: "log-6",
        timestamp: "2026-02-25T16:45:00Z",
        userId: "eng-2",
        userName: "Michael Chang",
        role: "Engineer",
        actionType: "POST_CLOSE",
        targetEntity: "post-3",
        result: "success",
        details: "Marked 'Non-invasive Glucose Monitoring Wearable' as Partner Found"
    },
    {
        id: "log-7",
        timestamp: "2026-02-25T10:00:00Z",
        userId: "doc-1",
        userName: "Dr. James Miller",
        role: "Healthcare Professional",
        actionType: "MEETING_REQUEST",
        targetEntity: "post-1",
        result: "success",
        details: "Meeting request sent for 'AI-Assisted Detection of Arrhythmia'"
    },
    {
        id: "log-8",
        timestamp: "2026-02-24T23:30:00Z",
        userId: "unknown",
        userName: "Unknown",
        role: "N/A",
        actionType: "LOGIN_FAILED",
        targetEntity: "session",
        result: "failure",
        details: "Failed login attempt — invalid .edu email"
    },

    {
        id: "log-10",
        timestamp: "2026-02-22T09:00:00Z",
        userId: "eng-4",
        userName: "Dr. Lars Nilsson",
        role: "Engineer",
        actionType: "POST_CREATE",
        targetEntity: "post-6",
        result: "success",
        details: "Created 'Wearable Seizure Detection System'"
    },
    {
        id: "log-11",
        timestamp: "2026-02-20T10:00:00Z",
        userId: "eng-1",
        userName: "Dr. Sarah Chen",
        role: "Engineer",
        actionType: "POST_CREATE",
        targetEntity: "post-1",
        result: "success",
        details: "Created 'AI-Assisted Detection of Arrhythmia in ECG'"
    },
    {
        id: "log-12",
        timestamp: "2026-02-20T09:00:00Z",
        userId: "eng-1",
        userName: "Dr. Sarah Chen",
        role: "Engineer",
        actionType: "LOGOUT",
        targetEntity: "session",
        result: "success",
        details: "User logged out"
    }
];
